chore: [UM-11] add a new functionality to call bulk users retrieve
Zextras/carbonio-user-management-sdk pull request #1
Opened 2023-03-09 09:06 UTC by ppolito-zextras

2023-03-09 09:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/Zextras/carbonio-user-management-sdk?pullRequest=1) <br/>All committers have signed the CLA.

2023-03-09 09:43 UTC, nomanAli95 requested changes

2023-03-09 09:43 UTC, nomanAli95 commented on carbonio-user-management-sdk.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Please remember to not commit or push this kind of file, this is a module settings file created by IntelliJ, so remove it from this PR and add a line in .gitignore for the iml extension

2023-03-09 09:43 UTC, nomanAli95 commented on pom.xml.versionsBackup
> +<!--
same as above, please check and remove this from the PR

2023-03-09 09:43 UTC, nomanAli95 commented on src/main/java/com/zextras/carbonio/usermanagement/UserManagementClient.java
> +    HttpGet request = new HttpGet(userManagementURL + getUsersEndpoint + usersUUID);
Please check usersUUID, I don't think you can pass it in this way. The correct way to pass a list of ids in a GET http request is: `/user/?ids=1&ids=2&ids=3`

2023-03-09 15:10 UTC, nomanAli95 requested changes, later dismissed

2023-03-09 15:10 UTC, nomanAli95 commented on src/main/java/com/zextras/carbonio/usermanagement/UserManagementClient.java
> +        new UserNotFound("The cookie: \"" + cookie + "\" is not valid")
I think this is not the correct error you should return here, it depends on how you handle this request on the user-management side. Infact I noticed that the yaml on the carbonio-user-management side has only 400 bad request error, so here you couldn't use "The cookie is not valid" as message error.

2023-03-09 15:17 UTC, lucagasparini1981 requested changes

2023-03-09 15:17 UTC, lucagasparini1981 commented on src/main/java/com/zextras/carbonio/usermanagement/UserManagementClient.java
> +    HttpGet request = new HttpGet(getRequest.get());
Request URL is not valid. You must have an URL like this: 
`http://localhost:10000/users?userIds={id1}&userIds={id2} ...`
You can use usersUUID.stream().map(...).collect(Collectors.joining(...)) to build the string of queries' parameters.

2023-03-09 15:17 UTC, lucagasparini1981 commented on carbonio-user-management-sdk.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Please remove this file from the repository

2023-03-17 10:05 UTC, domenicostragliotto requested changes

2023-03-17 10:05 UTC, domenicostragliotto commented on src/main/java/com/zextras/carbonio/usermanagement/UserManagementClient.java
> +        new UserNotFound("The cookie: \"" + cookie + "\" is not valid")
The Exception message is not coherent with the exception

2023-03-17 11:26 UTC, domenicostragliotto submitted a review, later dismissed

2023-03-21 11:43 UTC, domenicostragliotto approved these changes, later dismissed

2023-03-21 11:46 UTC, federicorispo approved these changes

2023-03-22 07:40 UTC, lucagasparini1981 approved these changes

2023-03-23 11:03 UTC, lucagasparini1981 approved these changes, later dismissed

2023-03-23 11:23 UTC, federicorispo approved these changes, later dismissed

2023-03-23 11:30 UTC, federicorispo approved these changes

2023-03-23 11:30 UTC, domenicostragliotto approved these changes

2023-03-23 11:51 UTC, lucagasparini1981 approved these changes

2023-03-23 11:51 UTC, merged